# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Akan spellchecker"
ak = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Akan, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ak = "TRANSLATE: A spellchecker for Akan, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ak"

[windows]
system_product_code = "{F8F6F9C9-7513-456C-94B3-BCB5A11CA9E9}_is1"
legacy_product_codes = [
    { value = "E37C9158-F70F-4CE1-9989-E526B3DB1ECB", kind = "nsis" },
    { value = "CC9083D6-18CD-49D9-9B57-41A37DF4E2E9", kind = "nsis" }
]

[package.speller]
name = "Akan"
version = "0.1.1"

[package.grammar]
name = "Akan"
version = "0.1.0"

[package.tts-text-proc]
name = "Akan"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
