template = "https://github.com/giellalt/template-lang-und"
rev_id = 269
template_sha = "c43b39fe5507de4cc3a96e60743ab44578e61fd2"

[replacements]
__GLOTTOLOG_ID__ = "akan1250"
__REPO__ = "lang-aka"
__UND2C__ = "ak"
__UNDEFINED__ = "Akan"
__UND__ = "aka"
