template = "https://github.com/giellalt/template-lang-und"
rev_id = 276
template_sha = "c9932c142bad82b28a2c8b49e60ad8895a749b1e"

[replacements]
__GLOTTOLOG_ID__ = "akan1250"
__REPO__ = "lang-aka"
__UND2C__ = "ak"
__UNDEFINED__ = "Akan"
__UND__ = "aka"
